version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
  mongo:
    image: "mongo"
    restart: always
    #ports:
    # - "27017:27017"
  rabbitmq:
     image: "rabbitmq:alpine"
     restart: always
     #ports:
     # - "5672:5672"